"""empty message

Revision ID: e009c0d7433e
Revises: 
Create Date: 2021-06-21 12:05:04.900614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e009c0d7433e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('n_victorias', sa.Integer(), nullable=False),
    sa.Column('n_derrotas', sa.Integer(), nullable=False),
    sa.Column('n_empates', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('partidos',
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('equipo_a', sa.Integer(), nullable=False),
    sa.Column('equipo_b', sa.Integer(), nullable=False),
    sa.Column('porcentaje_1', sa.Float(), nullable=False),
    sa.Column('porcentaje_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_a'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['equipo_b'], ['equipos.id_equipo'], ),
    sa.PrimaryKeyConstraint('id_partido')
    )
    op.create_table('usuario',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('usuario', sa.String(length=70), nullable=False),
    sa.Column('contrasenia', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=False),
    sa.Column('dinero_en_cuenta', sa.Float(), nullable=False),
    sa.Column('ult_inicio_sesion', sa.DateTime(), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('apuestas',
    sa.Column('id_apuesta', sa.Integer(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id_partido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_apuesta')
    )
    op.create_table('solicitudes',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('monto_solicitado', sa.Float(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['usuario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('tarjeta_de_credito',
    sa.Column('id_tarjeta', sa.Integer(), nullable=False),
    sa.Column('n_tarjeta', sa.String(length=1000), nullable=False),
    sa.Column('ccv', sa.Integer(), nullable=False),
    sa.Column('titular', sa.String(length=1000), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_tarjeta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarjeta_de_credito')
    op.drop_table('solicitudes')
    op.drop_table('apuestas')
    op.drop_table('usuario')
    op.drop_table('partidos')
    op.drop_table('rol')
    op.drop_table('equipos')
    # ### end Alembic commands ###
